### ISSUE TITLE
Tracks with png minimap crashes the game

### ISSUE THREAD

**Issue by AndreDK7** [Indev450/SRB2Kart-Saturn#136]
As the name implies. I've been hosting RA Extended in my dedicated servers and until Saturn v6.2 was never a issue. But after v7, Cosmic Eclipse and Cosmic Eclipse Classic who uses png minimap crashes the game. Tried to run the game only with this mod loaded on my windows and same error occurred. Here's the log line.

![image](https://github.com/user-attachments/assets/43468b36-93e0-4424-823d-aa8e344af4ff)

**Comment by alufolie91** [comment]
Technically, its intended behaviour for the game to "crash" when discovers a png file in an addon, to make mappers/authors aware that they did not convert their lumps properly to a format the game can read, since png lumps are not supported in kart.
The issue with RA Extended is, a png file of the maps minimap has been mistakenly used as a map marker, not for the minimap itself. Vanilla kart just skipped the marker files entirely and didnt read them, while the new map data loading system indeed does read the marker files aswell
While this technically is an isssue with the addon itself, this change in behaviour was not intentional and we are working on a fix.

**Comment by alufolie91** [comment]
should be resolved with https://github.com/Indev450/SRB2Kart-Saturn/releases/tag/v7.1

**Comment by AndreDK7** [comment]
It is. Cosmic Eclipse and Cosmic Eclipse Classic, both with .png minimap, aren't crashing the game anymore. Thanks!
