### ISSUE TITLE
Saturn 5.1 64bit - replays hitching consistently

### ISSUE THREAD

**Issue by tummyache123** [Indev450/SRB2Kart-Saturn#99]
Hello! I had reached out in the Kart Krew Discord to try and find a resolution to this, but after some troubleshooting, it looks like the issue may be with the Saturn client. I attempted to run the vanilla client to compare, but I get an unable to start error when trying to run it now. If I can move my downloads and replays to a fresh install without breaking anything, let me know and I can try that to test.

Using the replay controls, I was able to go frame by frame using `perfstats 1` to find one of the frames where the replay is hitching. If we go by the replay frame advance, it's 156 frames until the next hitch occurs. I did it until the next hitch and it was 151 frames, so around 151-156 frames between hitches. I have the game FPS capped to my refresh rate which is 165.

![image](https://github.com/Indev450/SRB2Kart-Saturn/assets/70869203/a3124926-f151-4471-aad2-dc1a5cf15926)

This hitching happens consistently in the Saturn client but ONLY during replays. This does not happen during normal gameplay.

Let me know if there is any other information I can provide. Thank you in advance and thank you to everyone for your work!

**Comment by alufolie91** [comment]
oki we already talked a little in kk discord, since this is kinda a weird issue i cannot replicate, i really suggest trying out other replays and checking if it also still happens in the vanilla client.
since you use the 64bit version of saturn it means you have to fresh install vanilla since the dlls are incompatible due to vanilla only providing a 32bit version (hence it cant start with those)
just so we can see if it is client related or perhaps just a general kart thing

**Comment by alufolie91** [comment]
alr gonna close this, as this somewhat got resolved in the discord (well not really resolved but its not a saturn client specific thing for that matter)
